name: root-colors-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/root-colors/src/*.ts'
  push:
    branches:
      - main
    paths:
      - 'packages/root-colors/src/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm test -w 'stylelint-root-colors'
